include $(THEOS)/makefiles/common.mk

BUNDLE_NAME = FeishuAutoStatusPrefs

FeishuAutoStatusPrefs_FILES = FeishuAutoStatusPrefs.m
FeishuAutoStatusPrefs_FRAMEWORKS = UIKit
FeishuAutoStatusPrefs_PRIVATE_FRAMEWORKS = Preferences
FeishuAutoStatusPrefs_INSTALL_PATH = /Library/PreferenceBundles
FeishuAutoStatusPrefs_CFLAGS = -fobjc-arc

include $(THEOS_MAKE_PATH)/bundle.mk
